server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/chicken_store"
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true